// <auto-generated />
using System;
using ChartChecker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChartChecker.Data.Migrations
{
    [DbContext(typeof(ChartCheckerDbContext))]
    [Migration("20200108183048_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChartChecker.Models.Database.ChartCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChartType");

                    b.Property<DateTime>("EventDateTime");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Store");

                    b.Property<string>("UserEmail");

                    b.HasKey("Id");

                    b.ToTable("ChartCheck");
                });
#pragma warning restore 612, 618
        }
    }
}
