// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace ChartChecker.Backend.Data.Migrations
{
    [DbContext(typeof(ChartCheckerDbContext))]
    partial class ChartCheckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChartChecker.Backend.Models.Database.ChartCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventTime");

                    b.Property<string>("ImagePath");

                    b.Property<string>("StoreName");

                    b.Property<string>("UniqueId");

                    b.Property<string>("UserEmail");

                    b.HasKey("Id");

                    b.ToTable("ChartCheck");
                });
#pragma warning restore 612, 618
        }
    }
}
